### ISSUE TITLE
Experiment E-GEOD-109159 doesn't seem to have any metadata

### ISSUE THREAD

**Issue by wbazant** [ebi-gene-expression-group/scxa-experiment-page-tsne-plot-view#8]
The single cell portal is very pretty! I saw a couple of experiments, and some of them have metadata whereas others don't, e.g. E-ENAD-13 has inferred cell types, but E-GEOD-109159 doesn't have any.

It would be interesting if the visualization knew what metadata the experiment has and e.g. let me highlight parts of t-SNE by inferred cell types in E-ENAD-13, and didn't try to load any metadata in E-GEOD-109159. 

Right now it's a bit of a surprise what the popup will say after I hover on the cell on the left, and when I see that "loading metadata" doesn't ever show any metadata it makes me think something might be wrong with the page.

**Comment by alfonsomunozpomer** [comment]
Thank you for your feedback! ;)

We’re aware that the tooltip currently needs a bit of polish. Actually it’s a consequence of making it fully asynchronous, but we want to make it better.

Also, one of the features currently in development is to colour cells by metadata, not just by clusters produced by SC3. It’s one of the features high in our priority list. Stay tuned!
